server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thinker
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.itcast.service.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5